language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
env:
  - DJANGO=1.11.15
  - DJANGO=2.0.10
  - DJANGO=2.1.5
install:
 - pip install -U pip setuptools
 - pip install -r requirements.txt -r requirements-dev.txt
 - pip install Django==$DJANGO
#before_script:
script:
  - python setup.py code_quality
  - python setup.py test
  - python setup.py install
matrix:
  exclude:
    - env: DJANGO=2.0.10
      python: "2.7"
    - env: DJANGO=2.1.5
      python: "2.7"
    - env: DJANGO=2.1.5
      python: "3.4"
