#!/bin/bash

BASE_DIR=debian/restauth
CONFIG_DIR=/etc/restauth

declare -a files
files=$(find debian/ | grep localsettings.py$)

if [[ ! -d ${BASE_DIR}${CONFIG_DIR} ]]; then
	mkdir -p ${BASE_DIR}${CONFIG_DIR}
fi

set -x
for file in $files; do
	mv  $file ${BASE_DIR}${CONFIG_DIR}
	ln -s ${CONFIG_DIR}/localsettings.py $file
done
#
#echo $files
