#!/bin/sh

set -e
set -x

if [ "$1" = "configure" ]; then
	[ -e "/etc/restauth/settings.py" ] || exit 0
	[ $(grep -c __SECRET_KEY__ /etc/restauth/settings.py) -gt 0 ] || exit 0
	
	key=$(cat /dev/urandom | base64 | head -n 1 | sed 's/\//\\\//g')
	sed -i "s/__SECRET_KEY__/$key/" /etc/restauth/settings.py
fi

#DEBHELPER#
