#!/bin/sh

set -e

USERNAME=restauth
SETTINGS=/etc/restauth/settings.py

case "$1" in
	configure)

	# add system user:
	adduser --quiet --system --group --no-create-home --disabled-login $USERNAME
	
	chown root:$USERNAME $SETTINGS
	chmod o-rwx $SETTINGS
	chmod o-wx $SETTINGS

	# replace __SECRET_KEY__ with randomly generated string:
	[ -e "$SETTINGS" ] || break
	[ $(grep -c __SECRET_KEY__ $SETTINGS) -gt 0 ] || break
	
	key=$(cat /dev/urandom | base64 | head -n 1 | sed 's/\//\\\//g')
	sed -i "s/__SECRET_KEY__/$key/" $SETTINGS
	;;
esac

#DEBHELPER#
