#!/usr/bin/env python
#
# -*- coding: utf-8 -*-
#
# This file is part of RestAuth (https://restauth.net).
#
# RestAuth is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RestAuth is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RestAuth.  If not, see <http://www.gnu.org/licenses/>.
#
# 
# Watch number of accounts on RestAuth.
#
#%# family=auto
#%# capabilities=autoconf

import os, sys

if 'DJANGO_SETTINGS_MODULE' not in os.environ:
	os.environ['DJANGO_SETTINGS_MODULE'] = 'RestAuth.settings'

if len( sys.argv ) > 1 and sys.argv[1] == 'autoconf':
	try:
		from django.conf import settings
		dir( settings )
		print( 'yes' )
		sys.exit(0)
	except ImportError:
		print( 'no (cannot import django settings)' )
		sys.exit(1)

from RestAuth.Users.models import ServiceUser

if len( sys.argv ) > 1 and sys.argv[1] == 'config':
	print( """graph_title Number of RestAuth accounts
graph_args --base 1000 -l 0
graph_vlabel no. of accounts
graph_category restauth
total.label total no. of accounts""" )
	qs = ServiceUser.objects.values( 'algorithm' ).distinct()
	if len(qs) > 0:
		for result in qs:
			algo = result['algorithm']
			print( '%s.label no. of accounts with %s hash'%(algo,algo ) )
	sys.exit(0)

from django.db.models import Count
qs = ServiceUser.objects.values( 'algorithm' ).annotate( Count('algorithm') )
total = 0
for result in qs:
	total += result['algorithm__count']
	print( '%s.value %s'%(result['algorithm'], result['algorithm__count']) )

print( 'total.value %s'%total )
